docs/sdk-reference/go.md
I was just experimenting with the Go SDK and noticed that it was not possible to just copy-paste the HTTP Proxy example. This change fixes that.
My IDE automatically trims trailing whitespaces, so there are actually two commits here:
1. Remove all unnecessary trailing whitespace.
2. Fix proxy example.
These can be split up in two pull requests if desired.
=> Golang proxy fix

website/docs/sdk-reference/ios.md
https://trello.com/c/OYW2q6bl/308-ios-doksiba-docs-gen-code-menjen-be-a-swift-package-manager
This PR adds the missing SDK installation option for Swift Package Manager
=> Add swift pkg manager to install options

website/docs/advanced/troubleshooting.md, website/docs/sdk-reference/python.md
Python SDK's auto polling mode may not work with uWSGI web server. I added some not to the python sdk's docs and to the troubleshooting section too.
=> uwsgi docs

website/docs/advanced/team-management/auto-assign-users.md, website/docs/advanced/team-management/domain-verification.md, website/docs/advanced/team-management/saml/identity-providers/adfs.md, website/docs/advanced/team-management/saml/identity-providers/auth0.md, website/docs/advanced/team-management/saml/identity-providers/azure-ad.md, website/docs/advanced/team-management/saml/identity-providers/google.md, website/docs/advanced/team-management/saml/identity-providers/okta.md, website/docs/advanced/team-management/saml/identity-providers/onelogin.md, website/docs/advanced/team-management/saml/overview.md
Nginx puts a trailing slash which breaks the page links on subpages. So, I used absolute paths instead.
=> Absolute links, trailing slash fiesta

website/docs/sdk-reference/android.md, website/docs/sdk-reference/dart.md, website/docs/sdk-reference/elixir.md, website/docs/sdk-reference/go.md, website/docs/sdk-reference/ios.md, website/docs/sdk-reference/java.md, website/docs/sdk-reference/js-ssr.md, website/docs/sdk-reference/js.md, website/docs/sdk-reference/node.md, website/docs/sdk-reference/overview.md, website/docs/sdk-reference/php.md, website/docs/sdk-reference/python.md, website/docs/sdk-reference/ruby.md
Replace old travis badges with the new gh action badges. Add Dart pub dev badge.
=> Use the new gh action badges

website/docs/sdk-reference/elixir.md
In the elixir sdk evaluation logs moved back to debug level. We updated the samples in the docs too.
Evaluation log example's  loglevel should be debug.
=> logging fix on elixir sdk page

website/docs/sdk-reference/node.md
None.
Reading the docs for node I found that the `pollIntervalSeconds` range was actually `[-Number.MAX_SAFE_INTEGER+1, 1]` instead of the (as I understand) the desirable range: `[1, Number.MAX_SAFE_INTEGER]`.
No applicable.
=> docs: Typo on `pollIntervalSeconds` docs

website/docs/sdk-reference/php.md
Add type hints to PHP custom cache implementation.
=> Add type hints to PHP custom cache implementation

website/docs/advanced/code-references/overview.md
- Explaining the deleted flags warning on the CLI's code reference scanning.
- Intro of the `--exclude-flag-keys` scan option.
=> CLI scan deleted flags

website/docs/sdk-reference/java.md
Our CW Roxana Halati caught this while playing around with feature flags in Java.
=> compile is now deprecated and removed completely Gradle 7+

website/docs/sdk-reference/csharp.md
Related to https://github.com/configcat/.net-sdk/pull/42
=> Adds a warning to .NET SDK docs about TLS configuration

website/docusaurus.config.js
Updated `editUrl` variable in `docusaurus.config.js` to a readable link (Removing edit from the link)
When this PR is merged:
The **Edit this page** link on each page will be changed as follows:
**Before**: https://github.com/configcat/docs/edit/master/website/docs/sdk-reference/kotlin.md (Requires GitHub Auth)
**After**: https://github.com/configcat/docs/blob/master/website/docs/sdk-reference/kotlin.md (Does not require Auth)
**Reason for change**: Because accessing the edit link requires GitHub authentication, SE Ranking reports its as a 429 error when it audits the page as shown below:
As a side note, this edit link can also be hidden from each page by removing the `editUrl` variable from `docusaurus.config.js` as mentioned here: …
=> Updated editUrl variable

website/docs/getting-started.md, website/docs/requests.md
Remove duplicate H1s and fix heading hierarchy.
Reason for change: This was in the weekly SE Ranking audit report:
=> Remove duplicate h1s

website/docs/advanced/caching.md, website/docs/advanced/team-management/saml/overview.md, website/docs/advanced/team-management/team-management-basics.md, website/docs/sdk-reference/overview.md
Added missing H2s to the following `.md` files in the docs. There are a few more `.md` files that should be fixed similarly. Treat this as a first PR.
- website/docs/advanced/team-management/team-management-basics.md
- website/docs/advanced/caching.md
- website/docs/advanced/team-management/saml/overview.md
- website/docs/sdk-reference/overview.md
=> Add missing h2 tags

website/docs/advanced/team-management/auto-assign-users.md, website/docs/advanced/team-management/domain-verification.md, website/docs/advanced/team-management/saml/identity-providers/adfs.md, website/docs/advanced/team-management/saml/identity-providers/auth0.md, website/docs/advanced/team-management/saml/identity-providers/azure-ad.md, website/docs/advanced/team-management/saml/identity-providers/google.md, website/docs/advanced/team-management/saml/identity-providers/okta.md, website/docs/advanced/team-management/saml/identity-providers/onelogin.md, website/docs/advanced/team-management/single-sign-on-sso.md, website/docs/integrations/overview.md
Add missing H2s to the following `.md` files.
**Reason for change**: Reported in the weekly SE Ranking audit report
1. website/docs/integrations/overview.md
2. website/docs/advanced/team-management/domain-verification.md
3. website/docs/advanced/team-management/single-sign-on-sso.md
4. website/docs/advanced/team-management/auto-assign-users.md
5. website/docs/advanced/team-management/saml/identity-providers/azure-ad.md
6. website/docs/advanced/team-management/saml/identity-providers/adfs.md
7. website/docs/advanced/team-management/saml/identity-providers/google.md
8. website/docs/advanced/team-management/saml/identity-providers/okta.md
9. website/docs/advanced/team-management/saml/identity-providers/auth0.md
10. website/docs/advanced/team-management/saml/identity-providers/onelogin.md
=> Add missing h2s

website/docs/service/status.md
Fix the missing H2 tag issue.
This issue was found in last week's SE ranking report.
=> Fix missing h2 tag issue

website/src/schema-markup/sdk-reference/ios.json
Add missing `totalTime `property to iOS SDK Schema Markup.
Ticket: <https://trello.com/c/gKFceB0K>
@sigewuzhere , This seems to only be missing for the iOS Schema Markup.
Snapshot of the issue this PR fixes:
=> Add missing totalTime property

website/docs/sdk-reference/csharp.md
This page was reported by our SE Ranking tool to have the same title and description as: https://configcat.com/docs/sdk-reference/dotnet/
=> SEO Fix: Update Title and Description for C# SDK Reference page

website/docs/sdk-reference/csharp.md
Fixed: Non-canonical pages in XML sitemap.
Reason for change:
Our weekly SE ranking report showed the following crawling issue:
- Non-canonical pages in XML sitemap - https://configcat.com/docs/sdk-reference/csharp/
=> SEO Fix: Non-canonical pages in XML sitemap

website/docs/sdk-reference/js-ssr.md, website/docs/sdk-reference/node.md
Add synchronous getValue docs to Node and JS SSR SDKs.
=> Add synchronous getValue docs to JS SDKs (part 2)

website/docs/advanced/proxy/overview.md
Add docs for proxy [default options location](https://github.com/configcat/configcat-proxy/releases/tag/v0.1.6).
=> Add docs for proxy default options location

website/docs/sdk-reference/php.md
Updated the PHP SDK docs with the changes from [v8.1.0](https://github.com/configcat/php-sdk/releases/tag/v8.1.0).
=> Update PHP docs with latest changes

website/docs/sdk-reference/dotnet.md
Update .NET SDK docs (Catnip)
https://trello.com/c/OKRxYw2A
Only some text including a few links has been added to the .NET SDK reference.
=> Update .NET SDK docs (Catnip)

website/docs/sdk-reference/python.md
Fix function named argument in python.md
Changed the override samples. The samples should work now.
=> Fix function named argument in python.md

website/docs/sdk-reference/kotlin.md
The Kotlin Override section was extended with a new Settings option.
https://trello.com/c/Il9EgN4l/354-kotlin-settings-object-data-soruce
On the app, no test is required. The change only affects the Kotlin SDK.
=> Kotlin Override section extended with new Settings option.

website/docs/news.md
=> News for OpenFeature providers

website/docs/news.md
Adding the resource order news to docs
=> Order news

website/docs/advanced/proxy/endpoints.md, website/docs/advanced/proxy/grpc.md, website/docs/sdk-reference/go.md
- Documentation of `v9.0.0` Go SDK release (CatNip support).
- Documentation of related Proxy changes (includes CatNip support).
=> Docs of recent Go SDK and Proxy changes

website/docs/advanced/targeting.md, website/docs/getting-started.md
Fixes a few code samples that are not valid any more because of the changes to the JS SDK.
n/a
You may test that the changed code snippets work. (Just let me know if you need any help with that.)
=> Fix broken code samples

website/docs/advanced/config-v2-migration-guide.md, website/docs/advanced/config-v2-sdk-compatibility.md, website/docs/advanced/config-v2.md
advanced/config-v2-migration-guide
advanced/config-v2-sdk-compatibility
advanced/config-v2
Check the above pages and the links on them
=> Docs for Beta

website/docs/advanced/config-v2-migration-guide.md, website/docs/advanced/config-v2-sdk-compatibility.md, website/docs/advanced/config-v2.md
Updating Config V2
- Config V2 overview 
- Migration guide
=> Updating Config V2

website/docs/sdk-reference/android.mdx, website/versioned_docs/version-V1/sdk-reference/android.mdx
Remove misleading logging dependency example from the Android SDK Logging section.
The example was misleading because not just the slf4j-android can be used as an slf4j implementation. Our sample apps use two different solutions as well.
[GitHub issue](https://github.com/configcat/android-sdk/issues/48)
From the Logging section a code example is removed. v1 and v2 modified as well.
=> Android SDK - Remove misleading logging dependency example.

website/docs/subscription-plan-limits.mdx, website/versioned_docs/version-V1/subscription-plan-limits.mdx
We may occasionally increase the Targeting Rule comparison value length (chars) limit for an Organization, but I think it is not a good idea to advertise it as "If you hit a technical limit we will increase it for you". It could cause confusions.
I removed the asterisks from the  Targeting Rule comparison value length (chars) limit on the Subscription Plan Limits page.
=> Sub plan limits fix

website/docusaurus.config.ts, website/package-lock.json, website/package.json, website/src/client-modules/img-zoom/index.ts, website/src/client-modules/img-zoom/zoom.scss, website/src/css/custom.scss
This PR replaces the image zoom functionality with a solution that doesn't transform images, so texts on them won't be blurry upon zooming in.
Before:
After:
- Check zoomable images.
=> Replace image zoom with a solution that don't transform images

website/src/client-modules/img-zoom/index.ts, website/src/client-modules/img-zoom/zoom.scss
This PR fixes: 
1. Wrong positioning of the zoomed-in image when the holding container is too narrow.
Before:
After:
2. Pressing the browser's back button didn't close the zoomed-in image correctly.
Play with image zoom in different page sizes & back button.
=> Fix zoomed image position / browser back bug

website/docs/advanced/notifications-webhooks.mdx, website/docs/advanced/team-management/auto-assign-users.mdx, website/docs/advanced/team-management/domain-verification.mdx, website/docs/integrations/zapier.mdx, website/docs/main-concepts.mdx, website/docs/news.mdx, website/docs/sdk-reference/android.mdx, website/docs/sdk-reference/cpp.mdx, website/docs/sdk-reference/elixir.mdx, website/docs/sdk-reference/go.mdx, website/docs/sdk-reference/ios.mdx, website/docs/sdk-reference/js-ssr.mdx, website/docs/sdk-reference/js.mdx, website/docs/sdk-reference/unreal.mdx, website/versioned_docs/version-V1/advanced/notifications-webhooks.mdx, website/versioned_docs/version-V1/advanced/team-management/auto-assign-users.mdx, website/versioned_docs/version-V1/advanced/team-management/domain-verification.mdx, website/versioned_docs/version-V1/integrations/zapier.mdx, website/versioned_docs/version-V1/main-concepts.mdx, website/versioned_docs/version-V1/news.mdx, website/versioned_docs/version-V1/sdk-reference/android.mdx, website/versioned_docs/version-V1/sdk-reference/cpp.mdx, website/versioned_docs/version-V1/sdk-reference/elixir.mdx, website/versioned_docs/version-V1/sdk-reference/go.mdx, website/versioned_docs/version-V1/sdk-reference/ios.mdx, website/versioned_docs/version-V1/sdk-reference/js-ssr.mdx, website/versioned_docs/version-V1/sdk-reference/js.mdx, website/versioned_docs/version-V1/sdk-reference/unreal.mdx
Removed `:` character from docs titles.
=> Remove ':' character from titles

website/docs/advanced/notifications-webhooks.mdx, website/versioned_docs/version-V1/advanced/notifications-webhooks.mdx
Webhooks now can specify ##ChangedBy## in the content and it will be replaced by the user's email and name who made the changes.
https://trello.com/c/1rTjg9QS/228-who-changed-a-flag-webhook-variable
=> Webhook changed by

website/docs/sdk-reference/java.mdx
Added the new ClientReadyState parameter to the onClientReady hook in the Java SDK.
=> Update java sdk onClientReady hook with ClientReadyState parameter

website/docs/sdk-reference/android.mdx
Update android sdk onClientReady hook with ClientReadyState parameter
=> Update android sdk onClientReady hook with ClientReadyState parameter

website/docs/sdk-reference/overview.mdx, website/versioned_docs/version-V1/sdk-reference/overview.mdx
Add Rust SDK to the overview page.
- n/a
- n/a
=> Add Rust SDK to the overview page

website/docs/sdk-reference/java.mdx
Add logFilter option and Log Filter section to the Java SDK doc.
Add logFilter option to the list and Log Filter section to the Java SDK doc.
Add only to the new V2 doc.
=> Add logFilter option and Log Filter section to the SDK doc.

website/docs/integrations/amplitude.mdx, website/versioned_docs/version-V1/integrations/amplitude.mdx
Replaced broken link: https://www.docs.developers.amplitude.com/experiment/ with https://amplitude.com/docs/experiment
n/a
What part of the application were affected by the changes?
`/website/docs/integrations/amplitude.mdx` 
Check if the updated link is ok
=> Fix broken URL link in amplitude integration documentation

website/docs/advanced/code-references/bitbucket-pipe.mdx, website/docs/advanced/code-references/circleci-orb.mdx, website/docs/advanced/code-references/github-action.mdx, website/docs/advanced/code-references/overview.mdx, website/versioned_docs/version-V1/advanced/code-references/bitbucket-pipe.mdx, website/versioned_docs/version-V1/advanced/code-references/circleci-orb.mdx, website/versioned_docs/version-V1/advanced/code-references/github-action.mdx, website/versioned_docs/version-V1/advanced/code-references/overview.mdx
Added docs for the new `--usage-patterns` argument of the `scan` CLI command.
=> Add docs of additional usage patterns

website/docs/sdk-reference/android.mdx, website/docs/sdk-reference/cpp.mdx, website/docs/sdk-reference/ios.mdx, website/docs/sdk-reference/js-ssr.mdx, website/docs/sdk-reference/js.mdx, website/docs/sdk-reference/kotlin.mdx, website/docs/sdk-reference/react.mdx, website/docs/sdk-reference/unreal.mdx, website/versioned_docs/version-V1/sdk-reference/android.mdx, website/versioned_docs/version-V1/sdk-reference/cpp.mdx, website/versioned_docs/version-V1/sdk-reference/ios.mdx, website/versioned_docs/version-V1/sdk-reference/js-ssr.mdx, website/versioned_docs/version-V1/sdk-reference/js.mdx, website/versioned_docs/version-V1/sdk-reference/kotlin.mdx, website/versioned_docs/version-V1/sdk-reference/react.mdx, website/versioned_docs/version-V1/sdk-reference/unreal.mdx
Clarifies that all SDK keys are read-only.
https://configcat-community.slack.com/archives/C01C9T8G3EU/p1723027076841479
Only the https://configcat.com/docs/sdk-reference/js/#sensitive-information-handling section changed, but that section changed for all SDK documentation.
=> Based on the feedback of Richard Gill @ community slack

website/docs/integrations/overview.mdx, website/versioned_docs/version-V1/integrations/overview.mdx, website/versioned_sidebars/version-V1-sidebars.json
Integration sidenav ordering
https://trello.com/c/Cn6vyL4i/1213-integration-sidenav-ordering
=> Integration sidenav ordering + name differences

website/docs/sdk-reference/dotnet.mdx, website/docs/sdk-reference/java.mdx
Documentation for two upcoming developments in the .NET SDK: 
* https://github.com/configcat/.net-sdk/pull/95
* https://github.com/configcat/.net-sdk/pull/94
* https://trello.com/c/IxCFbq2j
* https://trello.com/c/L6VitCBe
The .NET SDK reference has been changed, including some new links.
=> .NET SDK custom log filter & platform compatibility docs

website/docs/advanced/config-v2-migration-guide.mdx, website/versioned_docs/version-V1/advanced/config-v2-migration-guide.mdx
Makes some text bold in the Config V2 migration guide to make it easier for the reader to get the key information.
https://trello.com/c/2hLGc87J
Only text formatting has changed in the Config V2 migration guide.
=> Highlight key information in Config V2 migration guide

website/docs/sdk-reference/android.mdx, website/docs/sdk-reference/go.mdx, website/docs/sdk-reference/java.mdx, website/docs/sdk-reference/js.mdx, website/docs/sdk-reference/openfeature/dotnet.mdx, website/docs/sdk-reference/openfeature/go.mdx, website/docs/sdk-reference/openfeature/java.mdx, website/docs/sdk-reference/openfeature/js.mdx, website/docs/sdk-reference/openfeature/node.mdx, website/docs/sdk-reference/openfeature/overview.mdx, website/docs/sdk-reference/openfeature/php.mdx, website/docs/sdk-reference/openfeature/python.mdx, website/docs/sdk-reference/openfeature/rust.mdx, website/sidebars.ts, website/versioned_docs/version-V1/sdk-reference/android.mdx, website/versioned_docs/version-V1/sdk-reference/go.mdx, website/versioned_docs/version-V1/sdk-reference/java.mdx, website/versioned_docs/version-V1/sdk-reference/js.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/dotnet.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/go.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/java.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/js.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/node.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/overview.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/php.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/python.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/rust.mdx, website/versioned_sidebars/version-V1-sidebars.json
This PR adds a new `OpenFeature Providers` section under the `SDK References` menu that lists and documents all the ConfigCat providers.
- Docs -> SDKs -> SDK References -> OpenFeature Providers
=> Add OpenFeature providers to SDK reference

.github/CODEOWNERS, website/docs/integrations/bitbucket.mdx, website/docs/integrations/bitrise.mdx, website/docs/integrations/circleci.mdx, website/docs/integrations/github.mdx, website/docs/sdk-reference/overview.mdx, website/sidebars.ts, website/src/pages/index.js, website/versioned_docs/version-V1/integrations/bitbucket.mdx, website/versioned_docs/version-V1/integrations/bitrise.mdx, website/versioned_docs/version-V1/integrations/circleci.mdx, website/versioned_docs/version-V1/integrations/github.mdx, website/versioned_docs/version-V1/sdk-reference/overview.mdx, website/versioned_sidebars/version-V1-sidebars.json
Fix Android SDK name and order.
=> Fix Android SDK name and order

website/docs/sdk-reference/dotnet.mdx, website/docs/sdk-reference/openfeature/dotnet.mdx, website/docs/sdk-reference/openfeature/js.mdx, website/docs/sdk-reference/openfeature/node.mdx, website/docs/sdk-reference/overview.mdx, website/versioned_docs/version-V1/sdk-reference/dotnet.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/dotnet.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/js.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/node.mdx, website/versioned_docs/version-V1/sdk-reference/overview.mdx
This PR fixes a bunch of major and minor errors in the code samples in the docs of OpenFeature providers mentioned in the title. (It's worth mentioning in particular that currently the OF provider for web package doesn't include a bundle that can be referenced directly, via a `<script>` tag in browsers. This is something that should be addressed at OF's side. Here I just removed that part from the docs for now.)
Also, gets rid of mentions of .NET Core as it is obsolete now.
n/a
Ideally, the new code samples should be verified by executing them.
=> Fix .NET, JavaScript and Node.js OpenFeature provider code samples

website/docs/advanced/code-references/overview.mdx, website/docs/sdk-reference/js-ssr.mdx, website/docs/sdk-reference/openfeature/go.mdx, website/docs/sdk-reference/openfeature/java.mdx, website/versioned_docs/version-V1/advanced/code-references/overview.mdx, website/versioned_docs/version-V1/sdk-reference/js-ssr.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/go.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/java.mdx
Small typo fixes in the code references docs and js-ssr lambda block restructure.
Before:
After:
=> Small typo fixes and js-ssr lambda block restructure

website/docs/news.mdx, website/versioned_docs/version-V1/news.mdx
=> Disable 2fa news

website/docs/advanced/proxy/endpoints.mdx, website/versioned_docs/version-V1/advanced/proxy/endpoints.mdx
Add Rust SDK to Proxy supported SDKs / fix 'eval-all' sample request.
=> Add Rust SDK to Proxy supported SDKs / fix 'eval-all' sample request

website/docs/sdk-reference/js-ssr.mdx, website/docs/sdk-reference/js.mdx, website/docs/sdk-reference/node.mdx, website/docs/sdk-reference/react.mdx, website/versioned_docs/version-V1/sdk-reference/js-ssr.mdx, website/versioned_docs/version-V1/sdk-reference/js.mdx, website/versioned_docs/version-V1/sdk-reference/node.mdx, website/versioned_docs/version-V1/sdk-reference/react.mdx
Adds documentation for the query string flag override feature introduced in the React SDK.
Also, corrects a few minor mistakes.
https://trello.com/c/5zOq7X4K
New text has been added to the Flag Overrides section of the React SDK reference.
=> Add docs for query string flag override feature

website/docs/advanced/code-references/bitbucket-pipe.mdx, website/docs/advanced/code-references/bitrise-step.mdx, website/docs/advanced/code-references/circleci-orb.mdx, website/docs/advanced/team-management/auto-assign-users.mdx, website/docs/advanced/team-management/domain-verification.mdx, website/docs/advanced/team-management/saml/identity-providers/adfs.mdx, website/docs/advanced/team-management/saml/identity-providers/auth0.mdx, website/docs/advanced/team-management/saml/identity-providers/azure-ad.mdx, website/docs/advanced/team-management/saml/identity-providers/cloudflare.mdx, website/docs/advanced/team-management/saml/identity-providers/google.mdx, website/docs/advanced/team-management/saml/identity-providers/okta.mdx, website/docs/advanced/team-management/saml/identity-providers/onelogin.mdx, website/docs/integrations/amplitude.mdx, website/docs/integrations/jira.mdx, website/docs/integrations/segment.mdx, website/docs/integrations/zapier.mdx, website/src/css/custom.scss, website/versioned_docs/version-V1/advanced/team-management/auto-assign-users.mdx, website/versioned_docs/version-V1/advanced/team-management/domain-verification.mdx, website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/adfs.mdx, website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/auth0.mdx, website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/azure-ad.mdx, website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/cloudflare.mdx, website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/google.mdx, website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/okta.mdx, website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/onelogin.mdx, website/versioned_docs/version-V1/integrations/amplitude.mdx, website/versioned_docs/version-V1/integrations/jira.mdx, website/versioned_docs/version-V1/integrations/segment.mdx, website/versioned_docs/version-V1/integrations/zapier.mdx
Renamed the image border css and added it to integrations where a frame was needed.
- The following integration pages changed (bitbucket, amplitude, bitrise, circle ci, jira, zapier, twilio segment)
=> Img border rework

website/docs/sdk-reference/kotlin.mdx
Updated the Kotlin SDK onClientReady Hook description based on Kotlin SDK 4.1.0 changes.
[Trello ticket](https://trello.com/c/D6uM4Bxw/402-java-android-kotlin-sdk-rework-onclientready-hook-and-implement-waitforready)
Only the v2 docs changed.
=> Update Kotlin SDK hooks onClientReady description.

website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx
API docs V2 only, no version dropdown
https://trello.com/c/JQFxgM6k/1294-docs-n%C3%A1l-az-api-doksin%C3%A1l-ne-legyen-verzi%C3%B3-v%C3%A1laszt%C3%B3
=> API docs V2 only, no version dropdown

website/docs/targeting/targeting-rule/user-condition.mdx
Point out that text comparators are case sensitive
https://trello.com/c/JOFXhU5H
n/a
=> Point out that text comparators are case sensitive

website/docs/integrations/intellij.mdx, website/docs/integrations/overview.mdx, website/sidebars.ts, website/src/pages/index.js, website/versioned_docs/version-V1/integrations/intellij.mdx, website/versioned_docs/version-V1/integrations/overview.mdx, website/versioned_sidebars/version-V1-sidebars.json
- Update Intellij Marketplace links in the docs.
- Added Intellij docs to side bar and overview.
- V1 and V2 changes
- IntelliJ docs contain marketplace link
- Integration overview and side bar should list Jet Brains/Intellij Plugin
=> Update Intellij docs

.vscode/extensions.json, website/docs/network-traffic.mdx, website/docs/requests.mdx, website/versioned_docs/version-V1/network-traffic.mdx, website/versioned_docs/version-V1/requests.mdx
Additional texts for the request/network traffic pages
https://trello.com/c/uXJivsin/1323-proxy-%C3%A9s-quota-v%C3%A1s%C3%A1rl%C3%A1s-ker%C3%BClj%C3%B6n-be-erre-a-k%C3%A9t-helyre
Additional texts for the request/network traffic pages
=> request, network traffic additional texts

website/docs/sdk-reference/java.mdx, website/versioned_docs/version-V1/sdk-reference/java.mdx
Remove mention of deprecated `asyncRefresh` parameter from Java docs.
=> Remove mention of deprecated parameter

website/docs/sdk-reference/openfeature/go.mdx, website/versioned_docs/version-V1/sdk-reference/openfeature/go.mdx
Temporary go sdk version downgrade in the OpenFeature provider docs due to the latest provider is not released yet.
=> Temporary go sdk version downgrade due to the latest provider is not released yet

website/docs/news.mdx, website/docs/targeting/targeting-rule/flag-condition.mdx, website/docs/targeting/targeting-rule/segment-condition.mdx, website/src/css/custom.scss, website/src/pages/index.js, website/versioned_docs/version-V1/news.mdx
Sets `height: auto` for all `<img>`s in the `article` section, except for the ones that have the `no-auto-height` class.
This is necessary to maintain the aspect ratio of the images embedded according to new [Screenshot Guide](https://github.com/configcat-labs/content-wiki/blob/main/screenshot-guide.md).
n/a
Check a few pages with images. Everything should exactly the same as before.
=> Prepare site for screenshots created according to the new guide

website/docs/advanced/team-management/scim/overview.mdx, website/versioned_docs/version-V1/advanced/team-management/scim/overview.mdx
=> skip SCIM welcome email text cleanup

website/docs/advanced/notifications-webhooks.mdx
- Updated UI element names in the text
- Updated language to be more simple
- Tested variables
- Tested Headers
- Tested Signing (this contains bugs)
- Tested all links
- Not tested: Connecting to Slack, Connection to MS Teams
- Enforced the new UX guideline for the UI element names (this task was optional)
- https://trello.com/c/HsyThkyC/4205
- docs/advanced/notifications-webhooks/
=> docs review: Webhooks - major updates

website/docs/sdk-reference/php.mdx, website/versioned_docs/version-V1/sdk-reference/php.mdx
- Add cache warning to PHP SDK docs.
- https://trello.com/c/55lBRrAY/1427-php-sdk-cache-fontos-doksi-connect-app
=> Add cache warning to PHP SDK docs

website/docs/integrations/terraform.mdx, website/versioned_docs/version-V1/integrations/terraform.mdx
- Update the sample usage section in the Terraform integration document at the following link: https://configcat.com/docs/integrations/terraform/#sample-usage
Things that have changed:
- Using `version` in the provider block is deprecated.
- The "order" attribute is now required in the `configcat_setting` resource.
- [Update: Terraform Documentation](https://trello.com/c/GmuwagS8)
What part of the application was affected by the changes? 
- Update the sample usage section in the Terraform documentation
- Check if the changes are ok. I have tested the updated code sample and it works.
=> Update Terraform integration documentation
