configcat/docs

- docs/advanced/targeting.md
> Fix typo on targeting.md

- docs/advanced/notifications-webhooks.md
- docs/advanced/targeting.md
- docs/advanced/team-collaboration.md
- docs/advanced/user-object.md
Touched up some grammar, spelling, and rewrote some sentences.
> Iteration to ../docs/advanced

- website/docs/sdk-reference/elixir.md
- website/docs/sdk-reference/overview.md
- website/docusaurus.config.js
- website/sidebars.js
- website/src/pages/index.js
The first draft of the Elixir's docs. As mentioned here:
https://github.com/configcat/elixir-sdk/issues/4
> Adding Elixir’s Docs

- website/docs/advanced/caching.md
- website/docs/advanced/troubleshooting.md
- website/docs/requests.md
- website/sidebars.js
- website/src/pages/index.js
> MERGE - How to lower request count?

- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/csharp.md
- website/docs/sdk-reference/elixir.md
- website/docs/sdk-reference/go.md
- website/docs/sdk-reference/ios.md
- website/docs/sdk-reference/java.md
- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
- website/docs/sdk-reference/node.md
- website/docs/sdk-reference/php.md
- website/docs/sdk-reference/python.md
- website/docs/sdk-reference/ruby.md
Added github star buttons to the SDK documentations.
Open all SDKs' documentation and check the github star button at the top of the page.
> github star buttons

- website/docs/integrations/overview.md
- website/sidebars.js
https://trello.com/c/mcdKtqJ0/291-docs-legyen-integrations-overview-page
Integrations overview page.
Check the integrations overview page.
> Integrations overview

- website/docs/advanced/caching.md
- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/csharp.md
- website/docs/sdk-reference/elixir.md
- website/docs/sdk-reference/go.md
- website/docs/sdk-reference/ios.md
- website/docs/sdk-reference/java.md
- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
- website/docs/sdk-reference/node.md
- website/docs/sdk-reference/python.md
- website/docs/sdk-reference/ruby.md
> updating manual polling description

- website/docs/sdk-reference/elixir.md
Some compile fixes on the Elixir page
Check the sample code
> Elixir fixes

- website/docs/advanced/cli.md
This PR updates the CLI's docs with package installation options.
> Cli docs v2

- website/docs/advanced/targeting.md
Some explanation about Percentage targeting's stickiness and consistency
> stickyness

- website/docs/advanced/troubleshooting.md
no ticket
Fixes a broken link
- Visit /docs/advanced/troubleshooting
- Click data governance
> fixes a broken link

- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
https://trello.com/c/cWQHtuCx/344-docs
Updating all dependancies to latest.
Run a smoke test.
> September security updates

- website/docs/sdk-reference/ios.md
https://trello.com/c/5TtFIjjG/148-sdk-improvements-swift
Add `timeout setup` to the doc
> siwft timeout

- website/package-lock.json
- website/package.json
n/a
Novermber security updates
Smoke test
> Novermber security updates

- website/docs/advanced/cli.md
- website/src/pages/index.js
After some customer comments updating titles to help find stuff easier.
Titles on the home page
> Updating titles

- website/package-lock.json
- website/package.json
[Provide links to the tickets relating to this pull request.](https://trello.com/c/yUTWLTpz/503-docs)
Updating vulnerable dependencies.
Smoke test.
> December security review

- website/docs/advanced/notifications-webhooks.md
- website/src/pages/index.js
no tickets
- adds link pointing to the micorosft docs
- adds ##ChangeDetailsTeams## to the table of variables
- adds a link to the Integrations section of front page pointing to the MS Teams webhook description
Just a quick smoke test
> adds MS Teams related info

- website/docs/sdk-reference/java.md
- website/docs/sdk-reference/php.md
- website/src/css/custom.css
Docs-related follow-up changes from this [PR](https://github.com/configcat/php-sdk/pull/17).
> Update php docs regarding to the sdk imrpovements

- website/docs/sdk-reference/dart.md
- website/docs/sdk-reference/java.md
- website/docs/sdk-reference/php.md
- website/docusaurus.config.js
- website/sidebars.js
- website/src/pages/index.js
This PR adds documentation for the BRAND NEW DART/FLUTTER SDK 🎉 🥳
And fixes a few things in other parts.
> Add dart docs

- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/java.md
Docs changes related to [this](https://github.com/configcat/android-sdk/pull/13) PR.
> Docs part of android sdk improvements

- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/java.md
- website/docs/sdk-reference/php.md
SEO fixes - https links instead of http links.
> https links

- README.md
- website/docs/faq.md
- website/docs/sdk-reference/csharp.md
- website/src/schema-markup/faq.json
- website/src/schema-markup/sdk-reference/csharp.json
- website/src/schema-markup/sdk-reference/net.json
- website/src/schema-markup/sdk-reference/netcore.json
https://trello.com/c/5Qu6v86c/14-implement-schema-markup
I created a FAQ Page and a How-to Schema markup so we can talk about it and check if the content is alright. If it will be fine, we should add this to all sdk reference and we should investigate the pages where we should add it too.
I also added the generation and usage of schema markups to the readme.
> Schemamarkup

- website/docs/advanced/code-references/azure-devops.md
- website/docs/advanced/code-references/bitbucket-pipe.md
- website/docs/advanced/code-references/circleci-orb.md
- website/docs/advanced/code-references/github-action.md
- website/docs/advanced/code-references/gitlab-ci.md
- website/docs/advanced/code-references/overview.md
- website/docs/advanced/team-management/auto-assign-users.md
- website/docs/advanced/team-management/domain-verification.md
- website/docs/advanced/team-management/saml/identity-providers/adfs.md
- website/docs/advanced/team-management/saml/identity-providers/auth0.md
- website/docs/advanced/team-management/saml/identity-providers/azure-ad.md
- website/docs/advanced/team-management/saml/identity-providers/google.md
- website/docs/advanced/team-management/saml/identity-providers/okta.md
- website/docs/advanced/team-management/saml/identity-providers/onelogin.md
- website/docs/advanced/team-management/saml/overview.md
- website/docs/integrations/overview.md
- website/docs/sdk-reference/js.md
- website/src/pages/index.js
Alt text to images. Some minor text improvements
Provide a guideline about how to test the applied changes.
> Alt text to images

- website/docs/integrations/amplitude.md
- website/docs/integrations/bitbucket.md
- website/docs/integrations/circleci.md
- website/docs/integrations/datadog.md
- website/docs/integrations/github.md
- website/docs/integrations/jira.md
- website/docs/integrations/overview.md
- website/docs/integrations/slack.md
- website/docs/integrations/terraform.md
- website/docs/integrations/trello.md
- website/docs/integrations/vscode.md
- website/docs/integrations/zapier.md
- website/docs/integrations/zoho-flow.md
- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/csharp.md
- website/docs/sdk-reference/dart.md
- website/docs/sdk-reference/elixir.md
- website/docs/sdk-reference/go.md
- website/docs/sdk-reference/ios.md
- website/docs/sdk-reference/java.md
- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
- website/docs/sdk-reference/node.md
- website/docs/sdk-reference/overview.md
- website/docs/sdk-reference/php.md
- website/docs/sdk-reference/python.md
- website/docs/sdk-reference/ruby.md
Adding missing descriptions to documentation.
> descriptions

- website/docusaurus.config.js
Link to the search page.
Provide a guideline about how to test the applied changes.
> search link

- website/docs/faq.md
> Zombie -> Stale

- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
https://trello.com/c/0yMAuGjD/122-js-ssr-libekn%C3%A9l-a-custom-cache-nincs-a-doksiban
Create a custom cache section in JS and JS-SSR SDKs docs
Provide a guideline about how to test the applied changes.
> add custom cache section to js, js-ssr

- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
- website/docs/sdk-reference/node.md
Add `Debug` log level to JS related SDK docs.
> add debug level to JS related SDK docs

- website/docs/requests.md
[Provide links to the tickets relating to this pull request.](https://trello.com/c/PglMg7la/465-ide-felvenni-hogy-checkolj%C3%A1k-hogy-singletonk%C3%A9nt-van-e-haszn%C3%A1lva)
Use the client as a singleton
check the requests page
> Use the client as a singleton

- website/docs/sdk-reference/python.md
https://trello.com/c/FuPidQQt/160-sdk-loglevel-update-python
https://trello.com/c/i4HzNG0Z/105-sdk-getallvalues-python
https://trello.com/c/v1RVkza1/147-sdk-improvements-python
Pyhton docs update: logging + timeout + get_all_values + flag_overrides
> Python sdk improvements

- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
- website/docs/sdk-reference/node.md
Add flag overrides to JS-related SDK docs.
> Add flag overrides to JS related SDK docs

- website/docs/advanced/team-management/saml/overview.md
- website/docs/advanced/team-management/single-sign-on-sso.md
- website/docs/advanced/team-management/team-management-basics.md
- website/sidebars.js
> Adding SSO docs

- README.md
- package-lock.json
- website/package-lock.json
- website/package.json
Security updates in may.
smoke test
> May security updates

- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
- website/docs/sdk-reference/node.md
Update flag overrides docs in js related sdks.
> Update flag overrides docs in js related sdks

- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/ios.md
- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
Adding sensitive information handling and browser compatibility blocks.
> Sensitive info and browser compatibility

- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/csharp.md
- website/docs/sdk-reference/dart.md
- website/docs/sdk-reference/elixir.md
- website/docs/sdk-reference/go.md
- website/docs/sdk-reference/ios.md
- website/docs/sdk-reference/java.md
- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
- website/docs/sdk-reference/node.md
- website/docs/sdk-reference/php.md
- website/docs/sdk-reference/python.md
- website/docs/sdk-reference/ruby.md
Adding GetAllValues to all documentation.
Standardizing the order of the getAllKeys, getAllValues in the docs.
Adding the missing "Stop configcatclient" sections.
Formatting.
Provide a guideline about how to test the applied changes.
> Sdkdocsimprovements

- website/docs/sdk-reference/csharp.md
- website/docs/sdk-reference/go.md
Update go docs with local overrides.
> Update go docs with local overrides

- website/docs/advanced/code-references/bitrise-step.md
- website/docs/integrations/monday.md
> :pray: Updating integrations

- website/docs/sdk-reference/elixir.md
https://trello.com/c/6o97ddoY/154-sdk-improvements-elixir
https://trello.com/c/XCMtFgKo/165-sdk-loglevel-update-elixir
Update Elixir doc:
- Flag overrides
- timeout parameters
- get_all_values()
- Fix logging example
> Elixir improvements

- website/docs/integrations/monday.md
Adding the final link to the monday.com app.
> link and renamings

- website/docs/sdk-reference/ios.md
This PR syncs up docs for swift v9 changes.
> Sync up docs for swift v9 changes

- package-lock.json
- website/package-lock.json
- website/package.json
> August security updates

- website/docs/advanced/segmentation-and-segments.md
- website/docs/advanced/targeting.md
> Updating the docs of Segments

- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/ios.md
- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
reword the 'Sensitive information handling' paragraph
> 🙏  reword the 'Sensitive information handling' paragraph

- package-lock.json
- website/docs/advanced/cli.md
- website/docs/faq.md
- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/ios.md
- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
- website/docs/sdk-reference/overview.md
- website/docs/sdk-reference/react.md
- website/docusaurus.config.js
- website/sidebars.js
- website/src/pages/index.js
React SDK documentation.
Deployed to Cloudflare page: https://reactsdk.docs-xmy.pages.dev/docs/sdk-reference/react/
> React SDK docs

- website/docs/advanced/caching.md
I think this should be Time to Live (TTL), Time to Leave sounds like an exit strategy for when an employee is leaving a company 🤣
https://en.wikipedia.org/wiki/Time_to_live
> Update caching.md (TTL)

- website/docs/sdk-reference/dart.md
Documentation for the [newly introduced Dart SDK features](https://github.com/configcat/dart-sdk/pull/7).
> Documentation of new Dart SDK features

- website/docs/advanced/caching.md
- website/docs/advanced/code-references/azure-devops.md
- website/docs/advanced/code-references/bitbucket-pipe.md
- website/docs/advanced/code-references/bitrise-step.md
- website/docs/advanced/code-references/circleci-orb.md
- website/docs/advanced/code-references/github-action.md
- website/docs/advanced/code-references/gitlab-ci.md
- website/docs/advanced/code-references/overview.md
- website/docs/advanced/team-management/auto-assign-users.md
- website/docs/advanced/team-management/domain-verification.md
- website/docs/advanced/team-management/saml/identity-providers/adfs.md
- website/docs/advanced/team-management/saml/identity-providers/auth0.md
- website/docs/advanced/team-management/saml/identity-providers/azure-ad.md
- website/docs/advanced/team-management/saml/identity-providers/google.md
- website/docs/advanced/team-management/saml/identity-providers/okta.md
- website/docs/advanced/team-management/saml/identity-providers/onelogin.md
> Fix image borders

- website/package-lock.json
- website/package.json
> :pray: October security updates

- README.md
> :pray: Update README.md

- website/docs/advanced/cli.md
- website/docs/advanced/data-governance.md
- website/docs/advanced/public-api.md
- website/docs/advanced/segmentation-and-segments.md
- website/docs/advanced/targeting.md
- website/docs/advanced/team-management/saml/identity-providers/adfs.md
- website/docs/advanced/team-management/saml/identity-providers/auth0.md
- website/docs/advanced/team-management/saml/identity-providers/azure-ad.md
- website/docs/advanced/team-management/saml/identity-providers/google.md
- website/docs/advanced/team-management/saml/identity-providers/okta.md
- website/docs/advanced/team-management/saml/identity-providers/onelogin.md
- website/docs/advanced/team-management/saml/overview.md
- website/docs/advanced/troubleshooting.md
- website/docs/advanced/user-object.md
- website/docs/faq.md
- website/docs/requests.md
- website/docs/sdk-reference/python.md
- website/src/schema-markup/faq.json
While reading through the docs, I found some typos and grammar/wording mistakes. This PR contains my suggested corrections.
> Corrects several typos and grammar/wording mistakes

- website/docs/sdk-reference/ruby.md
Add force_refresh session to the ruby docs
> ruby force_refresh()

- website/docs/sdk-reference/dart.md
- website/docs/sdk-reference/ios.md
> Docs of new iOS SDK features

- website/docs/sdk-reference/ios.md
- website/docusaurus.config.js
Added Objective-C code samples to Swift SDK docs.
> Objc samples

- .gitignore
- website/docs/sdk-reference/cpp.md
- website/docs/sdk-reference/dart.md
> :pray: example -> samples

- website/docs/advanced/public-api.md
Replace Swagger Codegen with OpenAPI Generator in Public API docs.
> Swagger Codegen -> OpenAPI Generator

- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
- website/src/css/custom.css
- website/src/theme/CodeBlock/index.js
This PR sets default line number rendering on code blocks and enables image zooming.
> Render line numbers in code blocks & image zoom

- website/docusaurus.config.js
> :pray: Reordering the navbar based on a bug report

- website/docs/faq.md
Wrapped each cdn link in an inline code block.
**Before**:
**After**:
**Reason for change**:
SE ranking reports error 403 on these links.
**Result of change (SE Ranking)**
Will remove this false positive error.
> Wrapped each cdn link in an inline code block

- website/docs/sdk-reference/dotnet.md
Docs of new .NET SDK features.
> Docs of new .NET SDK features

- website/docs/sdk-reference/dart.md
- website/docs/sdk-reference/php.md
> Docs of new PHP SDK features

- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
- website/docs/sdk-reference/node.md
To match the messaging we have [here](https://android-hooks.docs-xmy.pages.dev/docs/sdk-reference/android/).
> Put JS notices into an info box

- website/src/schema-markup/faq.json
Updated question and answer in `faq.json`.
> Updated question and answer

- website/src/schema-markup/faq.json
Added answers to the following questions in `faq.json`.
1. Is it possible to pay ConfigCat via wire transfer?
2. How do I upgrade my ConfigCat billing plan?
3. How do I downgrade my ConfigCat billing plan?
4. How can I use ConfigCat at a discounted rate?
> Added additional FAQ data

- website/src/schema-markup/faq.json
Added answers to the following questions in `faq.json`.
1. How do I change the billing email address on my ConfigCat invoices?
2. How do I change my payment method on ConfigCat?
3. How do I change my billing information on ConfigCat?
4. The ChargeBee payment gets stuck on ConfigCat
5. The ChargeBee payment throws an error on ConfigCat
> Added additional FAQs data

- website/src/schema-markup/faq.json
Added answers to the following questions in `faq.json`.
- How do I cancel my ConfigCat account?
- How do I change my currency in ConfigCat?
- Is ConfigCat ISO certified?
- Which addresses should I whitelist for ConfigCat when setting up my firewall?
> Added additional questions and answers

- website/docs/glossary.md
- website/docs/glossary/devops-engineer.md
- website/src/pages/index.js
Creating the glossary section.
> Creating the Glossary

- website/src/schema-markup/faq.json
Added answers to the following questions.
1.  What are Zombie Flags in ConfigCat?
2.  What is the Zombie Flags Report in ConfigCat?
3.  I am not getting the Zombie Feature Flag email report from ConfigCat
> Add additional FAQ Data

- website/docs/sdk-reference/dart.md
- website/docs/sdk-reference/ios.md
- website/docs/sdk-reference/kotlin.md
Docs for the new caching behavior in Dart / Kotlin / Swift.
> Document new caching behavior in Dart / Kotlin / Swift

- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/cpp.md
- website/docs/sdk-reference/dart.md
- website/docs/sdk-reference/dotnet.md
- website/docs/sdk-reference/elixir.md
- website/docs/sdk-reference/go.md
- website/docs/sdk-reference/ios.md
- website/docs/sdk-reference/java.md
- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
- website/docs/sdk-reference/kotlin.md
- website/docs/sdk-reference/node.md
- website/docs/sdk-reference/php.md
- website/docs/sdk-reference/python.md
- website/docs/sdk-reference/react.md
- website/docs/sdk-reference/ruby.md
> :pray: Replacing GUID in SDK docs

- package-lock.json
- website/src/pages/index.js
> :pray: SEO audit fix

- website/docs/sdk-reference/dotnet.md
Update .NET SDK docs for the upcoming v7.1.0 release
> Update .NET SDK docs for v7.1.0

- website/docs/sdk-reference/node.md
Docs of new Node.js SDK features.
> Docs of new Node.js SDK features

- website/docs/sdk-reference/js.md
> Docs of new JS SDK features

- website/docs/sdk-reference/js-ssr.md
Docs of new JS SSR SDK features
> Docs of new JS SSR SDK features

- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/dart.md
- website/docs/sdk-reference/dotnet.md
- website/docs/sdk-reference/go.md
- website/docs/sdk-reference/ios.md
- website/docs/sdk-reference/java.md
- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
- website/docs/sdk-reference/kotlin.md
- website/docs/sdk-reference/node.md
- website/docs/sdk-reference/php.md
- website/docs/sdk-reference/python.md
> :pray: minor fixes in the docs

- website/docs/sdk-reference/cpp.md
- website/docs/sdk-reference/python.md
- website/docs/sdk-reference/ruby.md
Fixes grammar mistakes in the `Logging` section at:
- Python SDK
- Ruby SDK
- C++ SDK
> 🙏  fixes grammar

- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
> :pray: Adding google tag manager

- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/cpp.md
- website/docs/sdk-reference/dart.md
- website/docs/sdk-reference/dotnet.md
- website/docs/sdk-reference/go.md
- website/docs/sdk-reference/ios.md
- website/docs/sdk-reference/java.md
- website/docs/sdk-reference/kotlin.md
- website/docs/sdk-reference/php.md
- website/docs/sdk-reference/python.md
- website/docs/sdk-reference/ruby.md
Docs of new Ruby SDK features (offline/default_user/hooks/evaluation details).
> docs of ruby improvements + fixes

- website/docs/sdk-reference/python.md
> Python log

- website/docs/sdk-reference/node.md
Adding the node version badge to the documentation.
> Node version badge

- website/docs/faq.md
By now, we received a few questions from customers about the GDPR delete flow.
In this commit, the answers to their most basic questions are added to the FAQ.
> 🙏  add GDPR delete to the FAQ

- website/docs/sdk-reference/cpp.md
- website/docs/sdk-reference/dart.md
Docs of new C++ SDK features (offline/default_user/hooks/evaluation details).
> cpp docs update: hooks, default_user, online/offline

- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/java.md
Fixed **Mixed content** issue found in this Week's SE ranking report.
Files changed:
1. `website/docs/sdk-reference/java.md`
2. `website/docs/sdk-reference/android.md`
> Seo fix mixed content issue

- website/src/schema-markup/faq.json
Added [question and answer](https://configcat.com/docs/faq/#how-long-does-configcat-keep-my-data) to the `faq.json` file.
> Added missing question and answer

- website/src/schema-markup/sdk-reference/net.json
Update schema markup for dotnet to match the [documentation](https://configcat.com/docs/sdk-reference/dotnet/).
> Update schema for dotnet

- website/docs/sdk-reference/android.md
- website/src/schema-markup/sdk-reference/android.json
> Added android schema markup

- website/docs/sdk-reference/cpp.md
- website/src/schema-markup/sdk-reference/cpp.json
> Add C++ schema markup

- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/java.md
Java & Android SDK logging examples added to the documentation.
> Java & Android SDK logging examples added.

- website/docs/sdk-reference/dart.md
- website/src/schema-markup/sdk-reference/dart.json
> Add dart schema markup

- website/docs/sdk-reference/go.md
- website/src/schema-markup/sdk-reference/go.json
> Add Go Schema Markup

- website/docs/sdk-reference/ios.md
- website/src/schema-markup/sdk-reference/ios.json
> Add iOS Schema Markup

- website/docs/sdk-reference/python.md
This commit rollbacks Python logging changes: 
https://github.com/configcat/docs/commit/b6e6fd8f65319e6c14d0dfd15d422e91b6186cf8
This PR fixes this.
> python docs: python logging

- website/docs/sdk-reference/community/deno.md
Fixed a multiple H1 tags issue reported in this week's SE Ranking report.
> Fix multiple H1 tags SEO issue

- website/docs/sdk-reference/java.md
- website/src/schema-markup/sdk-reference/java.json
> Add Java schema markup

- website/docs/sdk-reference/js-ssr.md
- website/src/schema-markup/sdk-reference/js-ssr.json
Added: JS-SSR SDK Schema markup.
> Add JS-SSR SDK schema markup

- website/docs/sdk-reference/js.md
- website/src/schema-markup/sdk-reference/js.json
> Add JavaScript schema markup

- website/docs/sdk-reference/cpp.md
> Remove ; from cpp docs

- website/docs/integrations/overview.md
- website/docs/integrations/slack.md
> Slack review changes

- website/docs/sdk-reference/kotlin.md
- website/src/schema-markup/sdk-reference/kotlin.json
> Add kotlin SDK schema markup

- website/docs/sdk-reference/community/laravel.md
Just a simple update following the recent changes.
https://github.com/Pod-Point/laravel-configcat/releases/tag/3.0.0
> Update laravel.md for pod-point/laravel-configcat 3.0.0

- website/docs/sdk-reference/php.md
- website/src/schema-markup/sdk-reference/php.json
> Add: PHP SDK Schema Markup

- website/docs/sdk-reference/node.md
- website/src/schema-markup/sdk-reference/node.json
Add: Node.js SDK Schema markup
> Add: Node.js SDK Schema markup

- website/docs/sdk-reference/ruby.md
- website/src/schema-markup/sdk-reference/ruby.json
> Add: Ruby SDK schema markup

- website/docs/sdk-reference/python.md
- website/src/schema-markup/sdk-reference/python.json
Add: Python SDK schema markup.
> Add: Python schema markup

- website/docs/sdk-reference/react.md
- website/src/schema-markup/sdk-reference/react.json
> Add: React SDK schema markup

- website/docs/sdk-reference/community/deno.md
- website/src/schema-markup/sdk-reference/community/deno.json
> Add: deno SDK schema markup

- website/docs/sdk-reference/community/laravel.md
- website/src/schema-markup/sdk-reference/community/laravel.json
Add: Laravel SDK schema markup.
> Add: Laravel SDK schema markup

- website/docs/sdk-reference/dotnet.md
> Update .NET SDK documentation

- website/docs/sdk-reference/overview.md
> Add: Grammar fix

- website/docs/sdk-reference/dotnet.md
- website/docs/sdk-reference/js-ssr.md
- website/docs/sdk-reference/js.md
- website/docs/sdk-reference/node.md
- website/docs/sdk-reference/react.md
> Update JS SDK documentation

- website/docs/sdk-reference/python.md
> python shared cache

- website/docs/sdk-reference/android.md
- website/docs/sdk-reference/java.md
- website/docs/sdk-reference/kotlin.md
- Java SDK 
- Update logging example
- Android SDK
- Update logging example
- Update gradle example version
- Remove the deprecated code mentioned
- Kotlin SDK
- Update logging example
- Remove the deprecated code mentioned
> Update java android kotlin sdk

- website/docs/advanced/targeting.md
- website/docs/advanced/team-management/saml/identity-providers/adfs.md
- website/docs/advanced/team-management/saml/identity-providers/auth0.md
- website/docs/advanced/team-management/saml/identity-providers/azure-ad.md
- website/docs/advanced/team-management/saml/identity-providers/google.md
- website/docs/advanced/team-management/saml/identity-providers/okta.md
- website/docs/advanced/team-management/saml/identity-providers/onelogin.md
- website/docs/getting-started.md
- website/src/schema-markup/sdk-reference/android.json
- website/src/schema-markup/sdk-reference/community/deno.json
- website/src/schema-markup/sdk-reference/community/laravel.json
- website/src/schema-markup/sdk-reference/cpp.json
- website/src/schema-markup/sdk-reference/dart.json
- website/src/schema-markup/sdk-reference/elixir.json
- website/src/schema-markup/sdk-reference/go.json
- website/src/schema-markup/sdk-reference/ios.json
- website/src/schema-markup/sdk-reference/java.json
- website/src/schema-markup/sdk-reference/js-ssr.json
- website/src/schema-markup/sdk-reference/js.json
- website/src/schema-markup/sdk-reference/kotlin.json
- website/src/schema-markup/sdk-reference/net.json
- website/src/schema-markup/sdk-reference/node.json
- website/src/schema-markup/sdk-reference/php.json
- website/src/schema-markup/sdk-reference/python.json
- website/src/schema-markup/sdk-reference/react.json
- website/src/schema-markup/sdk-reference/ruby.json
Updated the dashboard URLs throughout the repo as requested in trello ticket: https://trello.com/c/gsOYTDOV.
> Updated dashboard URLs

- website/docs/advanced/config-v2-migration-guide.md
- website/package-lock.json
- website/sidebars.js
- website/src/pages/index.js
This is a minimal version of the mgration guide so it is linkable from the dashboard.
> Minimal migration guide 

- website/docs/main-concepts.md
- website/package-lock.json
> Text setting value misunderstanding

- website/docs/sdk-reference/overview.md
> Updating SDK overview

- website/docs/glossary.md
glossary developer advocate link pointing toward blog article
> added glossary dev advocate link

- website/docs/requests.md
> how to lower the network traffic

- website/docs/glossary.md
backlinked some glossary items to their landing pages
> backlinked some LPs

- website/docs/advanced/caching.md
- website/docs/sdk-reference/ruby.md
> ruby shared cache

- website/docs/network-traffic.md
- website/docs/requests.md
- website/sidebars.js
- website/src/pages/index.js
> Network Traffic page

- website/docs/faq.md
> 2FA FAQ extra

- website/docs/advanced/caching.md
- website/docs/sdk-reference/cpp.md
> C++ shared cache

- website/docs/advanced/caching.md
- website/docs/sdk-reference/go.md
Added consistent caching to the Go SDK docs and bumped to the latest version.
> Update Go docs

- website/docs/sdk-reference/js.md
Add docs of synchronous getValue of JS SDKs.
> Add docs of synchronous getValue of JS SDKs

- website/docs/faq.md
Added the extra FAQ question for https://trello.com/c/N9beQhmk
> added new FAQ question

- website/docs/glossary.md
Linked 6 new landing pages to the glossary. Added entry to glossary to those that didn't have any. Trello ticket [here](https://trello.com/c/Gzgirx66).
> linked 6 landing pages to glossary

- website/docs/network-traffic.md
> Adding table to network traffic docs

- website/docs/advanced/proxy/endpoints.md
- website/docs/advanced/proxy/overview.md
This PR documents the [default user attributes](https://github.com/configcat/configcat-proxy/pull/5) feature of the Proxy.
> Add proxy default attributes docs

- website/docs/advanced/caching.md
- website/docs/sdk-reference/dart.md
- website/docs/sdk-reference/ios.md
- website/docs/sdk-reference/php.md
- Add cache generalization docs for Dart / PHP / Swift.
- Add documentation for snapshots and synchronous feature flag evaluation in Swift.
> Cache generalization sdk docs

- website/docs/advanced/proxy/endpoints.md
- website/docs/advanced/proxy/overview.md
Minor fixes in the Proxy docs.
> Minor fixes in the Proxy docs

- website/docs/integrations/zoho-flow.md
> Zoho link update

- website/docs/advanced/proxy/overview.md
Add proxy global offline option docs.
> Add proxy global offline option docs

- website/docs/advanced/proxy/endpoints.md
Update Proxy CORS related docs.
> Update Proxy CORS related docs

- website/docs/advanced/cli.md
Add docs for the new features introduced in [ConfigCat CLI v1.9.0](https://github.com/configcat/cli/releases/tag/v1.9.0).
> Update CLI docs

- website/docs/advanced/proxy/endpoints.md
Documentation for Proxy [CORS regex](https://github.com/configcat/configcat-proxy/pull/13) pattern support. 
Not much to test here.
> Proxy CORS regex pattern support documentation

- website/package-lock.json
> oct security

- website/docs/glossary.md
- website/docs/glossary/alpha-testing.md
Check the alpha testing page linked from the glossary.
> Adding Alpha testing page to glossary

- website/docs/glossary.md
- website/docs/glossary/what-is-a-staging-environment.md
This PR adds the term Staging Environment to the glossary.
https://trello.com/c/JB0Ae98P
Check the glossary and the staging environment item.
> Adding staging env to the glossary

- website/docusaurus.config.js
Update Google Tag Manager ID to ConfigCat - Live GTM container.
https://trello.com/c/9xlvOtTc/1-m%C3%A9rni-a-hirdet%C3%A9seket-pl-google-ads
https://trello.com/c/khgcjmMC/808-tracking-fix
Check the tracking events in GTM and GA
> update google tag manager id

- website/docs/advanced/cli.md
This PR adds an example for chaining resource IDs with the CLI.
n/a
n/a
> Add example for chaining resource IDs with the CLI

- website/docs/news.md
> Add proxy to the news

- website/docs/subscription-plan-limits.md
- website/docusaurus.config.js
Smartlook should be inactive after this.
> Temporarily inactivating smartlook

- website/docs/sdk-reference/python.md
Update .NET SDK docs (Catnip)
https://trello.com/c/F7RpcumF/316-catnip-python
Only some text including a few links has been added to the .NET SDK reference.
> Update Python SDK docs (Catnip)

- .vscode/settings.json
- website/docs/advanced/config-v2-sdk-support-table.md
This table shows which SDK versions support Config V2.
https://trello.com/c/WxOCefzs/264-doksi-legyen-egy-tablazat-a-catnipet-supportalo-sdkkrol
Check the page: /advanced/config-v2-sdk-support-table
> V2 SDK support table

- website/docs/advanced/code-references/bitrise-step.md
- website/docs/news.md
- website/docs/sdk-reference/community/laravel.md
- website/docs/sdk-reference/ios.md
Links to the docs should not start with https://configcat.com/docs inside the docs
> Link fixes

- website/docs/advanced/code-references/azure-devops.md
- website/docs/advanced/code-references/bitbucket-pipe.md
- website/docs/advanced/code-references/circleci-orb.md
- website/docs/advanced/code-references/gitlab-ci.md
Updated the CI integration versions.
> Update the CI integration versions

- website/docs/integrations/bitbucket.md
- website/docs/integrations/circleci.md
- website/docs/integrations/datadog.md
- website/docs/integrations/github.md
- website/docs/integrations/jira.md
- website/docs/integrations/monday.md
- website/docs/integrations/terraform.md
- website/docs/integrations/trello.md
- website/docs/integrations/vscode.md
- website/docs/integrations/zapier.md
- website/docs/integrations/zoho-flow.md
Shorten page titles for some of doc pages. This was done to improve our docs SEO score. See the Trello ticket link below for more details.
[link to the Trello card](https://trello.com/c/PlSVyWkR)
What part of the application were affected by the changes? 
Titles shorten:
| Original Title                                                     | Original Title Length | Shortened Title                                              | Shortened Title Length |
|--------------------------------------------------------------------|-----------------------|--------------------------------------------------------------|------------------------|
| [CircleCI Orb - Scan source code for unused feature flags - ConfigCat Docs](https://configcat.com/docs/integrations/circleci/) | 78                    | …
> Shorten page titles for SEO

- website/docs/advanced/config-v2-sdk-support-table.md
- website/docs/advanced/proxy/endpoints.md
- website/docs/sdk-reference/java.md
Update the Java SDK docs  for v9.0.0 (Catnip)
https://trello.com/c/9ywJ2lbj/328-catnip-java-sdk
The SDK docs updated and the  config-v2-sdk-support-table.md
> Updated Java docs to v9.0.0 - Catnip

- website/docs/advanced/config-v2-sdk-compatibility.md
> sdk compatibility update

- website/docs/advanced/config-v2-sdk-compatibility.md
- website/docs/advanced/config-v2.md
Suggests a few minor improvements to Config V2 docs.
n/a
Only a few minor changes, see git diff
> Minor improvements to Config V2 docs

- website/docs/news.md
> Adding news for beta

- website/docs/sdk-reference/community/vue.md
- website/docs/sdk-reference/overview.md
- website/sidebars.js
- website/src/pages/index.js
- website/src/schema-markup/sdk-reference/community/vue.json
This pull request (PR) adds the Vue.js SDK to the documentation. Please refer to the Trello card linked below for more details.
[Trello Card Link](https://trello.com/c/uZDcYbaf)
The changes impact the following parts of the application:
- Relevant documentation data for the Vue.js SDK and supporting changes were added to the docs website.
Specifically:
- Main documentation data was added to: `website/docs/sdk-reference/community/vue.md`
- Links to the documentation were added to the sidebar and footer:
- `website/sidebars.js`
- `website/src/pages/index.js`
- Schema markup for the added documentation was also included.
Please test the following:
- Ensure the documentation is correctly rendered.
- Verify if the added footer link works as expected.
- Confirm that the added sidebar link …
> Add Vue.js SDK to the docs

- website/docs/sdk-reference/community/vue.md
Lali pointed out some issues found in the Vue.js SDK docs. This PR fixes those issues.
What part of the application were affected by the changes? 
The documentation page for the Vue.js SDK
- Check to see if all the code blocks are formatted and highlighted correctly.
- Check to see if the appropriate code language was set for each code block.
> Fix Vue.js SDK doc issues

- website/docs/sdk-reference/ruby.md
Fix wrong ruby example.
n/a
n/a
> Fix wrong ruby example

- website/docs/integrations/overview.md
- website/versioned_docs/version-V1/integrations/overview.md
Small integ page layout fix
https://trello.com/c/pAyp0j9M/1074-docs-bugs
> small layout fix

- website/docs/advanced/config-v2-sdk-compatibility.mdx
Update python sdk version in config-v2-sdk-compatibility
> Update python sdk version in config-v2-sdk-compatibility

- .vscode/settings.json
- website/docusaurus.config.ts
- website/package-lock.json
- website/package.json
- website/sidebars.ts
- website/tsconfig.json
Type safety, extra settings, vscode settings.
> Docusaurus V3 config improvements

- website/docusaurus.config.ts
> v2 noindex

- website/docs/advanced/config-v2-sdk-compatibility.mdx
- website/versioned_docs/version-V1/advanced/config-v2-sdk-compatibility.mdx
- Update Java and Android versions in the v2 compatibility table.
- Update Java and Android versions to the latest in the v2 compatibility table.
> Update Java and Android versions in the v2 compatibility table.

- website/docs/advanced/config-v2-sdk-compatibility.mdx
- website/versioned_docs/version-V1/advanced/config-v2-sdk-compatibility.mdx
Dart SDK version has been updated in the compatibility tables.
Dart SDK version has been updated in the compatibility tables. Now it should be v4.0.1
> Dart SDK version updated in the compatibility tables.

- website/src/css/custom.scss
This PR fixes this abomination:
> Fix broken code highlight

- website/docs/advanced/proxy/monitoring.mdx
- website/docs/advanced/proxy/overview.mdx
- website/versioned_docs/version-V1/advanced/proxy/monitoring.mdx
- website/versioned_docs/version-V1/advanced/proxy/overview.mdx
> Apply proxy v0.4.0 changes

- website/docs/advanced/proxy/endpoints.mdx
- website/docs/advanced/proxy/grpc.mdx
- website/docs/advanced/proxy/monitoring.mdx
- website/docs/advanced/proxy/overview.mdx
- website/versioned_docs/version-V1/advanced/proxy/endpoints.mdx
- website/versioned_docs/version-V1/advanced/proxy/grpc.mdx
- website/versioned_docs/version-V1/advanced/proxy/monitoring.mdx
- website/versioned_docs/version-V1/advanced/proxy/overview.mdx
Docs for Proxy [`v0.4.2`](https://github.com/configcat/configcat-proxy/pull/20) changes.
> Proxy v0.4.2 changes

- website/docs/faq.mdx
- website/versioned_docs/version-V1/faq.mdx
clarification of the DPA section in the FAQ
no trello card
The FAQ page
> clarification of the DPA section in the FAQ

- .prettierrc
- website/docs/advanced/config-v2-migration-guide.mdx
- website/docs/advanced/data-governance.mdx
- website/docs/purchase.mdx
- website/docs/requests.mdx
- website/docs/targeting/targeting-overview.mdx
- website/docs/targeting/targeting-rule/user-condition.mdx
- website/versioned_docs/version-V1/advanced/config-v2-migration-guide.mdx
- website/versioned_docs/version-V1/advanced/data-governance.mdx
- website/versioned_docs/version-V1/purchase.mdx
- website/versioned_docs/version-V1/requests.mdx
Addressing a few minor issues.
-
no need to test
> Minor fixes for Catnip

- website/docs/advanced/config-v2-sdk-compatibility.mdx
- website/docs/advanced/proxy/endpoints.mdx
- website/docs/sdk-reference/ios.mdx
- website/versioned_docs/version-V1/advanced/config-v2-sdk-compatibility.mdx
- website/versioned_docs/version-V1/advanced/proxy/endpoints.mdx
- website/versioned_docs/version-V1/sdk-reference/ios.mdx
Documentation changes related to the Swift config V6 update.
> Swift config V6 docs

- website/docs/news.mdx
- website/versioned_docs/version-V1/news.mdx
Adding customer survey to the news
> Customer survey news

- website/docs/advanced/config-v2-sdk-compatibility.mdx
- website/docs/advanced/proxy/endpoints.mdx
- website/versioned_docs/version-V1/advanced/config-v2-sdk-compatibility.mdx
- website/versioned_docs/version-V1/advanced/proxy/endpoints.mdx
Update minimum SDK versions in the relevant tables.
n/a
Nothing to test.
> Update minimum SDK versions

- website/docs/advanced/team-management/auto-assign-users.mdx
- website/docs/advanced/team-management/saml/identity-providers/adfs.mdx
- website/docs/advanced/team-management/saml/identity-providers/auth0.mdx
- website/docs/advanced/team-management/saml/identity-providers/azure-ad.mdx
- website/docs/advanced/team-management/saml/identity-providers/cloudflare.mdx
- website/docs/advanced/team-management/saml/identity-providers/google.mdx
- website/docs/advanced/team-management/saml/identity-providers/okta.mdx
- website/docs/advanced/team-management/saml/identity-providers/onelogin.mdx
- website/docs/advanced/team-management/team-management-basics.mdx
- website/docs/targeting/feature-flag-evaluation.mdx
- website/docs/targeting/percentage-options.mdx
- website/versioned_docs/version-V1/advanced/team-management/auto-assign-users.mdx
- website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/adfs.mdx
- website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/auth0.mdx
- website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/azure-ad.mdx
- website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/cloudflare.mdx
- website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/google.mdx
- website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/okta.mdx
- website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/onelogin.mdx
- website/versioned_docs/version-V1/advanced/team-management/team-management-basics.mdx
Fixing some grammar issues.
n/a
no need to test
> Fixing some grammar issues

- website/docs/advanced/proxy/overview.mdx
- website/versioned_docs/version-V1/advanced/proxy/overview.mdx
Update proxy v5 docs.
- Read through the Proxy's cache section.
> Update proxy v5 docs

- website/docs/news.mdx
- website/versioned_docs/version-V1/news.mdx
Adding news for Config v2.
n/a
check both news pages (v1 and v2)
> Config V2 News

- website/docusaurus.config.ts
Adding redirects from the old /V2 pages to the new / pages. Safety first!
> Adding V2 safety redirects

- website/docs/advanced/config-v2-sdk-compatibility.mdx
- website/docs/sdk-reference/android.mdx
- website/docs/sdk-reference/cpp.mdx
- website/docs/sdk-reference/dart.mdx
- website/docs/sdk-reference/elixir.mdx
- website/docs/sdk-reference/go.mdx
- website/docs/sdk-reference/ios.mdx
- website/docs/sdk-reference/java.mdx
- website/docs/sdk-reference/kotlin.mdx
- website/docs/sdk-reference/python.mdx
- website/docs/sdk-reference/ruby.mdx
- website/docs/sdk-reference/unreal.mdx
- website/versioned_docs/version-V1/advanced/config-v2-sdk-compatibility.mdx
- website/versioned_docs/version-V1/sdk-reference/android.mdx
- website/versioned_docs/version-V1/sdk-reference/cpp.mdx
- website/versioned_docs/version-V1/sdk-reference/dart.mdx
- website/versioned_docs/version-V1/sdk-reference/elixir.mdx
- website/versioned_docs/version-V1/sdk-reference/go.mdx
- website/versioned_docs/version-V1/sdk-reference/ios.mdx
- website/versioned_docs/version-V1/sdk-reference/java.mdx
- website/versioned_docs/version-V1/sdk-reference/kotlin.mdx
- website/versioned_docs/version-V1/sdk-reference/php.mdx
- website/versioned_docs/version-V1/sdk-reference/python.mdx
- website/versioned_docs/version-V1/sdk-reference/ruby.mdx
- website/versioned_docs/version-V1/sdk-reference/unreal.mdx
Minor corrections, mostly formatting.
n/a
Nothing to test.
> Minor corrections

- website/docs/sdk-reference/go.mdx
Update badges on the Go SDK docs.
> Update go badges

- .husky/pre-commit
- README.md
- website/package-lock.json
- website/package.json
Updated dependencies and removed unused packages.
https://trello.com/c/4GFBMWqC/1333-docs
Updated the fundamental packages, please smoke test the whole docs.
- images should be visible
- code snippets should appear correctly
- links should work
> April security fixes and cleanup of unused packages

- website/docusaurus.config.ts
- website/package-lock.json
- website/package.json
Reverted version update and set contextual search to true (v1, latest docs)
> revert version update

- .github/pull_request_template.md
- website/package.json
- website/testrobots.js
Adding robots.txt for cloudflare pages so the robots don't crawl them.
Also adding an extra check for the template.
> Adding robots txt for cloudflare pages

- website/docs/sdk-reference/php.mdx
- website/versioned_docs/version-V1/sdk-reference/php.mdx
> Update PHP badges

- website/docs/sdk-reference/js-ssr.mdx
- website/docs/sdk-reference/js.mdx
- website/docs/sdk-reference/node.mdx
- website/docs/sdk-reference/react.mdx
- website/versioned_docs/version-V1/sdk-reference/js-ssr.mdx
- website/versioned_docs/version-V1/sdk-reference/js.mdx
- website/versioned_docs/version-V1/sdk-reference/node.mdx
- website/versioned_docs/version-V1/sdk-reference/react.mdx
Added an instruction of custom logger implementation and setup to javascript based SDKs.
https://trello.com/c/L6VitCBe/396-custom-logger-implement%C3%A1ci%C3%B3-a-doksiban
> [JS-*] custom logger implementation

- website/docs/news.mdx
- website/versioned_docs/version-V1/news.mdx
ConfigCat Proxy release in the news
https://trello.com/c/ycR07mO3/60-configcat-proxy-release-announcement-news-slack
Check the news
> news: configcat proxy release

- website/docs/sdk-reference/cpp.mdx
- website/versioned_docs/version-V1/sdk-reference/cpp.mdx
Custom logger in cpp-sdk docs
https://trello.com/c/L6VitCBe/396-custom-logger-implement%C3%A1ci%C3%B3-a-doksiban
Check cpp SDK docs
> cpp sdk custom logger

- website/docs/advanced/proxy/endpoints.mdx
- website/docs/targeting/targeting-rule/user-condition.mdx
- website/versioned_docs/version-V1/advanced/proxy/endpoints.mdx
Our weekly SE Ranking report highlighted issues pertaining to broken URL links. This PR was made to remedy them.
[link to the Trello card](https://trello.com/c/ssc3WNgC)
What part of the application were affected by the changes? 
- Broken URL links.
- Check if the updated URL links work as expected.
> SEO Fixes (broken URL links)

- website/docs/sdk-reference/dart.mdx
- website/docs/sdk-reference/java.mdx
- website/docs/sdk-reference/kotlin.mdx
- website/versioned_docs/version-V1/sdk-reference/dart.mdx
- website/versioned_docs/version-V1/sdk-reference/java.mdx
- website/versioned_docs/version-V1/sdk-reference/kotlin.mdx
- updated custom logging-related sections in the Java/Dart/Kotlin SDK
- Java SDK - removed the misleading dependency suggestion
- Kotlin/Dart SDK - added MyCustomLogger dummy/example implementation
> Java kotlin dart logging

- website/docs/advanced/team-management/saml/identity-providers/azure-ad.mdx
- website/docs/advanced/team-management/saml/overview.mdx
- website/docs/advanced/team-management/single-sign-on-sso.mdx
- website/sidebars.ts
- website/versioned_docs/version-V1/advanced/team-management/saml/identity-providers/azure-ad.mdx
- website/versioned_docs/version-V1/advanced/team-management/saml/overview.mdx
- website/versioned_docs/version-V1/advanced/team-management/single-sign-on-sso.mdx
- website/versioned_sidebars/version-V1-sidebars.json
> Azure AD -> Entra ID

- website/docs/sdk-reference/kotlin.mdx
- website/versioned_docs/version-V1/sdk-reference/kotlin.mdx
Update kotlin version style to match kotlin 1.9
Fix the version style to match kotlin 1.9
> Update kotlin version style to match kotlin 1.9

- website/docs/news.mdx
- website/versioned_docs/version-V1/news.mdx
Adding news about webhook and product preference management
> Webhook, product prefernce news

- website/docs/integrations/mixpanel.mdx
- website/versioned_docs/version-V1/integrations/mixpanel.mdx
Consolidated Mixpanel docs to be the same format as the Google Analytics and Amplitude.
> Consolidate mixpanel docs

- website/docs/advanced/notifications-webhooks.mdx
- website/versioned_docs/version-V1/advanced/notifications-webhooks.mdx
Modified the order of the retries chapter and added ChangeDetailsSlack to the slack message.
> webhook docs improvement

- website/docs/integrations/overview.mdx
- website/versioned_docs/version-V1/integrations/overview.mdx
Adding the missing integrations to the integration overview
> Adding the missing integrations to the integration overview

- website/docs/integrations/amplitude.mdx
- website/docs/integrations/mixpanel.mdx
- website/versioned_docs/version-V1/integrations/amplitude.mdx
- website/versioned_docs/version-V1/integrations/mixpanel.mdx
Fixed a typo (evalated => evaluated)
> Fixed a typo (evalated => evaluated)

- website/docs/integrations/mixpanel.mdx
- website/versioned_docs/version-V1/integrations/mixpanel.mdx
Added the https://mixpanel.com/partners/integrations/configcat link to the docs.
> mixpanel links

- website/docs/advanced/cli.mdx
- website/docs/advanced/code-references/bitbucket-pipe.mdx
- website/docs/advanced/code-references/circleci-orb.mdx
- website/docs/advanced/code-references/github-action.mdx
- website/docs/advanced/code-references/overview.mdx
- website/versioned_docs/version-V1/advanced/cli.mdx
- website/versioned_docs/version-V1/advanced/code-references/bitbucket-pipe.mdx
- website/versioned_docs/version-V1/advanced/code-references/circleci-orb.mdx
- website/versioned_docs/version-V1/advanced/code-references/github-action.mdx
- website/versioned_docs/version-V1/advanced/code-references/overview.mdx
Docs for CLI scan alias patterns.
n/a
> Docs for CLI scan alias patterns

- website/docs/integrations/segment.mdx
- website/versioned_docs/version-V1/integrations/segment.mdx
> segment docs changes

- website/docs/integrations/amplitude.mdx
- website/docs/integrations/mixpanel.mdx
- website/docs/integrations/segment.mdx
- website/docs/sdk-reference/ruby.mdx
- website/versioned_docs/version-V1/integrations/amplitude.mdx
- website/versioned_docs/version-V1/integrations/mixpanel.mdx
- website/versioned_docs/version-V1/integrations/segment.mdx
- website/versioned_docs/version-V1/sdk-reference/ruby.mdx
Segment+analytics integrations code sample fixes
> Segment docs fixes

- website/docs/integrations/overview.mdx
- website/docs/integrations/segment.mdx
- website/docs/news.mdx
- website/sidebars.ts
- website/src/pages/index.js
- website/versioned_docs/version-V1/integrations/overview.mdx
- website/versioned_docs/version-V1/integrations/segment.mdx
- website/versioned_docs/version-V1/news.mdx
- website/versioned_sidebars/version-V1-sidebars.json
> Segment GA, news

- website/docs/integrations/google-analytics.mdx
- website/docs/sdk-reference/js-ssr.mdx
- website/versioned_docs/version-V1/integrations/google-analytics.mdx
- website/versioned_docs/version-V1/sdk-reference/js-ssr.mdx
Google analytics audience link fix and adding some recommendations for Next.js/aws lambda.
> next js and google analytics fixes

- website/docs/integrations/google-analytics.mdx
- website/versioned_docs/version-V1/integrations/google-analytics.mdx
> Google analytics link fix

- website/docs/sdk-reference/rust.mdx
- website/src/schema-markup/sdk-reference/rust.json
- website/versioned_docs/version-V1/sdk-reference/rust.mdx
> Rust schema markup

- website/docs/news.mdx
- website/versioned_docs/version-V1/news.mdx
> Rust SDK news

- website/docs/sdk-reference/java.mdx
Updates based on the latest API changes.
Updated the Log Filtering section based on the SDK changes.
> Java SDK Log Filtering section update

- website/docs/sdk-reference/unreal.mdx
v6 json description in unreal-sdk docs
> v6 json description in unreal-sdk docs

- website/docs/sdk-reference/unreal.mdx
- website/versioned_docs/version-V1/sdk-reference/unreal.mdx
> Fixes in unreal docs

- website/package-lock.json
- website/package.json
Package updates 2024/08
https://trello.com/c/UxbSyLcC/1456-docs
> Package updates 2024/08

- website/docs/integrations/amplitude.mdx
- website/docs/integrations/mixpanel.mdx
- website/docs/sdk-reference/go.mdx
- website/versioned_docs/version-V1/integrations/amplitude.mdx
- website/versioned_docs/version-V1/integrations/mixpanel.mdx
- website/versioned_docs/version-V1/sdk-reference/go.mdx
Fixup Go samples throughout the docs.
> Fixup Go samples throughout the docs

- website/docs/news.mdx
- website/versioned_docs/version-V1/news.mdx
Integration terraform+public api news
> Integration terraform+public api news

- website/docs/sdk-reference/unreal.mdx
- website/versioned_docs/version-V1/sdk-reference/unreal.mdx
Unreal SDK sample app link
Check the link
> unreal sdk sample app link

- azure-pipelines.yaml
Additional argument for docker build to be able to skip cache
> Additional argument for docker build to be able to skip cache

- website/docs/advanced/code-references/bitbucket-pipe.mdx
- website/docs/advanced/code-references/bitrise-step.mdx
- website/docs/advanced/code-references/circleci-orb.mdx
- website/docs/advanced/code-references/github-action.mdx
- website/versioned_docs/version-V1/advanced/code-references/bitbucket-pipe.mdx
- website/versioned_docs/version-V1/advanced/code-references/bitrise-step.mdx
- website/versioned_docs/version-V1/advanced/code-references/circleci-orb.mdx
- website/versioned_docs/version-V1/advanced/code-references/github-action.mdx
> Bitrise step update

- website/docs/news.mdx
- website/versioned_docs/version-V1/news.mdx
This PR adds the new OpenFeature providers to the news.
- Docs -> News
> Add new OpenFeature providers to news

- website/docs/sdk-reference/dotnet.mdx
- website/src/schema-markup/sdk-reference/java.json
- website/src/schema-markup/sdk-reference/js-ssr.json
- website/src/schema-markup/sdk-reference/js.json
- website/src/schema-markup/sdk-reference/net.json
- website/src/schema-markup/sdk-reference/node.json
- website/src/schema-markup/sdk-reference/react.json
- website/versioned_docs/version-V1/sdk-reference/dotnet.mdx
* Fixes NuGet badge in .NET SDK reference
* Fixes referencing schema json in .NET SDK reference
* Fixes broken/wrong links in SDK reference schemas
n/a
All the badges should show up in the .NET SDK reference now.
> Fix minor SDK reference-related issues

- website/docs/sdk-reference/android.mdx
- website/docs/sdk-reference/dart.mdx
- website/docs/sdk-reference/dotnet.mdx
- website/docs/sdk-reference/java.mdx
- website/docs/sdk-reference/openfeature/java.mdx
- website/docs/sdk-reference/openfeature/php.mdx
- website/docs/sdk-reference/php.mdx
- website/versioned_docs/version-V1/sdk-reference/android.mdx
- website/versioned_docs/version-V1/sdk-reference/dart.mdx
- website/versioned_docs/version-V1/sdk-reference/dotnet.mdx
- website/versioned_docs/version-V1/sdk-reference/java.mdx
- website/versioned_docs/version-V1/sdk-reference/openfeature/java.mdx
- website/versioned_docs/version-V1/sdk-reference/openfeature/php.mdx
- website/versioned_docs/version-V1/sdk-reference/php.mdx
Fix incorrect Java OpenFeature code samples. Also, I fixed some whitespaces in different code samples.
> Fix Java OpenFeature docs

- .github/pull_request_template.md
Add checkbox to remind about testing new code samples
n/a
n/a
> Add checkbox to remind about testing new code samples

- website/docs/sdk-reference/dotnet.mdx
- website/docs/sdk-reference/overview.mdx
- website/docs/sdk-reference/unity.mdx
- website/sidebars.ts
- website/src/pages/index.js
- website/src/schema-markup/sdk-reference/unity.json
- website/versioned_docs/version-V1/sdk-reference/dotnet.mdx
- website/versioned_docs/version-V1/sdk-reference/overview.mdx
- website/versioned_docs/version-V1/sdk-reference/unity.mdx
- website/versioned_sidebars/version-V1-sidebars.json
Adds a guide/reference for Unity.
n/a
A new item has been added to the SDK reference list. It should show up in the starting page and the side bar (when viewing both V1 and V2).
> Add docs for Unity

- website/docs/sdk-reference/unity.mdx
Fix broken link in Unity reference
n/a
n/a
> Fix broken link in Unity reference

- website/versioned_sidebars/version-V1-sidebars.json
Remove redundant item from V1 SDK references sidebar
n/a
n/a
> Remove redundant item from V1 SDK references sidebar

- website/docs/sdk-reference/community/deno.mdx
Adds an info box to the Deno SDK reference which mentions that users may consider the new JS SDK.
n/a
See the PR description.
> Mention the new JS SDK in the Deno SDK reference

- website/package-lock.json
> security dec 24

- website/docs/sdk-reference/android.mdx
- Update Android SDK with log filtering description.
[Trello link](https://trello.com/c/IxCFbq2j/405-log-filtering-unnecessary-garbage-reduction)
Android SDK V2 Logging extended with Log Filter section. Added logFilter to the options table.
> Update Android SDK with log filtering.

- website/package-lock.json
Security updates for February 2025
[Related Trello ticket](https://trello.com/c/ZobyIKXC)
What part of the application were affected by the changes?
- The outdated project dependencies in the `package-lock.json` file have been updated.
- Check if the docs works as expected.
> Security updates for February 2025

- website/docs/advanced/code-references/bitbucket-pipe.mdx
- website/docs/advanced/code-references/circleci-orb.mdx
- website/versioned_docs/version-V1/advanced/code-references/bitbucket-pipe.mdx
- website/versioned_docs/version-V1/advanced/code-references/circleci-orb.mdx
Update scan integration versions.
> Update scan integration versions

- website/docs/advanced/code-references/azure-devops.mdx
- website/docs/advanced/code-references/gitlab-ci.mdx
- website/versioned_docs/version-V1/advanced/code-references/azure-devops.mdx
- website/versioned_docs/version-V1/advanced/code-references/gitlab-ci.mdx
Use correct CLI version in integrations.
> Use correct CLI version in integrations

- website/docs/sdk-reference/openfeature/go.mdx
- website/versioned_docs/version-V1/sdk-reference/openfeature/go.mdx
Update OF provider sample to use the latest Go SDK with the latest provider.
> Update OF provider sample to use the latest Go SDK with the latest provider

- website/docs/advanced/migration-from-ld-translation.mdx
- website/docs/advanced/migration-from-ld.mdx
Applies guide text review changes + some minor corrections/improvements.
n/a
n/a
> Finalize Migration from LaunchDarkly docs

- website/docs/advanced/caching.mdx
- website/versioned_docs/version-V1/advanced/caching.mdx
Ensures suggested videos are shown only from the same channel.
- Check the video suggestions on site: /docs/advanced/caching/
> Ensures suggested videos are shown only from the same channel.

- website/docs/news.mdx
- website/versioned_docs/version-V1/news.mdx
Add news for LD migrator
n/a
n/a
> Add news for LD migrator

- website/docs/news.mdx
> Add launchdarkly alternative to the migrator news text

- website/docs/advanced/migration-from-ld-translation.mdx
- website/docs/advanced/migration-from-ld.mdx
As agreed with the marking team, this PR makes the following changes:
* Swap step 2 and 3 in the migration guide
* Improve limit exceeded message
Also, turns mentions of ConfigCat Dashboard into links in the migration guide + makes a few minor corrections.
n/a
n/a
> Corrections to LD migration docs

- website/docs/advanced/migration-from-launchdarkly-translation.mdx
- Check `Multi-contexts` link on `migration-from-launchdarkly-translation` site.
> Fix broken link in migration-from-launchdarkly-translation.mdx

- website/docusaurus.config.ts
> Point SCIM API docs to live URL

- .github/workflows/validate-document.yml
Attempt to fix validate-document.yml
n/a
n/a
> Attempt to fix validate-document.yml

- website/package-lock.json
- website/package.json
This reverts commit c9b401dd86452e0ad039b63bc95bdfbaf26acd1f.
> Revert "Security Updates - June 2025 (#555)"

- website/docs/advanced/caching.mdx
- website/docs/advanced/code-references/manual.mdx
- website/docs/advanced/code-references/overview.mdx
- website/docs/integrations/google-analytics.mdx
- website/versioned_docs/version-V1/advanced/caching.mdx
- website/versioned_docs/version-V1/advanced/code-references/manual.mdx
- website/versioned_docs/version-V1/advanced/code-references/overview.mdx
> Docs review kp

- website/docs/sdk-reference/kotlin.mdx
- Fix time usage in Kotlin SDK docs.
> Fix time usage in Kotlin SDK docs

- website/docs/sdk-reference/openfeature/kotlin.mdx
- website/versioned_docs/version-V1/sdk-reference/openfeature/kotlin.mdx
- Update Kotlin OF provider docs.
> Update Kotlin OF provider docs

- Dockerfile
> sonar update

- azure-pipelines.yaml
> artifact fix

- website/docusaurus.config.ts
- website/package-lock.json
- website/package.json
> llms plugin

- website/docs/advanced/proxy/endpoints.mdx
- website/docs/advanced/proxy/overview.mdx
> Fix misleading OFREP docs

- website/docs/sdk-reference/dotnet.mdx
- website/src/schema-markup/sdk-reference/net.json
- website/versioned_docs/version-V1/sdk-reference/dotnet.mdx
Update build status badge in .NET SDK reference
https://trello.com/c/pk2BORFQ
n/a
> Update build status badge in .NET SDK reference

- website/docs/advanced/mcp-server.mdx
> Update environment variable names in documentation of MCP server
